const teamNames: {} = {
    "Alberni Valley Bulldogs": {
        abbreviation: "AV",
        city: "Alberni Valley",
        goals: 0,
        logo: "https://assets.leaguestat.com/bchl/logos/16.png",
        penalties: 0,
        penalty_minutes: 0,
        powerplay_goals: 0,
        shots: 0,
        team_name: "Alberni Valley Bulldogs",
        venue: "Alberni Valley Multiplex"
    },
    "Chilliwack Chiefs": {
        abbreviation: "CHW",
        city: "Chilliwack",
        goals: 0,
        logo: "https://assets.leaguestat.com/bchl/logos/13.jpg",
        penalties: 0,
        penalty_minutes: 0,
        powerplay_goals: 0,
        shots: 0,
        team_name: "Chilliwack Chiefs",
        venue:"Chilliwack Coliseum"
    },
    "Coquitlam Express": {
        abbreviation: "COQ",
        city: "Coquitlam",
        goals: 0,
        logo: "https://assets.leaguestat.com/bchl/logos/9.jpg",
        penalties: 0,
        penalty_minutes: 0,
        powerplay_goals: 0,
        shots: 0,
        team_name: "Coquitlam Express",
        venue:"Poirier Sports and Leisure Centre"
    },
    "Cranbrook Bucks": {
        abbreviation: "CRA",
        city: "Cranbrook",
        goals: 0,
        logo: "https://assets.leaguestat.com/bchl/logos/39.jpg",
        penalties: 0,
        penalty_minutes: 0,
        powerplay_goals: 0,
        shots: 0,
        team_name: "Cranbrook Bucks",
        venue:"Western Financial Place"
    },
    "Cowichan Valley Capitals": {
        abbreviation: "CV",
        city: "Cowichan Valley",
        goals: 0,
        logo: "https://assets.leaguestat.com/bchl/logos/10.png",
        penalties: 0,
        penalty_minutes: 0,
        powerplay_goals: 0,
        shots: 0,
        team_name: "Cowichan Valley Capitals",
        venue:"Cowichan Community Centre"
    },
    "Langley Rivermen": {
        abbreviation: "LAN",
        city: "Langley",
        goals: 0,
        logo: "https://assets.leaguestat.com/bchl/logos/11.jpg",
        penalties: 0,
        penalty_minutes: 0,
        powerplay_goals: 0,
        shots: 0,
        team_name: "Langley Rivermen",
        venue:"George Preston Arena"
    },
    "Merritt Centennials": {
        abbreviation: "MER",
        city: "Merritt",
        goals: 0,
        logo: "https://assets.leaguestat.com/bchl/logos/15.png",
        penalties: 0,
        penalty_minutes: 0,
        powerplay_goals: 0,
        shots: 0,
        team_name: "Merritt Centennials",
        venue:"Nicola Valley Memorial Arena"
    },
    "Nanaimo Clippers": {
        abbreviation: "NAN",
        city: "Nanaimo",
        goals: 0,
        logo: "https://assets.leaguestat.com/bchl/logos/23.jpg",
        penalties: 0,
        penalty_minutes: 0,
        powerplay_goals: 0,
        shots: 0,
        team_name: "Nanaimo Clippers",
        venue:"Frank Crane Arena"
    },
    "Penticton Vees": {
        abbreviation: "PEN",
        city: "Penticton",
        goals: 0,
        logo: "https://assets.leaguestat.com/bchl/logos/12.png",
        penalties: 0,
        penalty_minutes: 0,
        powerplay_goals: 0,
        shots: 0,
        team_name: "Penticton Vees",
        venue:"South Okanagan Events Centre"
    },
    "Powell River Kings": {
        abbreviation: "PR",
        city: "Powell River",
        goals: 0,
        logo: "https://assets.leaguestat.com/bchl/logos/8.jpg",
        penalties: 0,
        penalty_minutes: 0,
        powerplay_goals: 0,
        shots: 0,
        team_name: "Powell River Kings",
        venue:"Hap Parker Arena"
    },
    "Prince George Spruce Kings": {
        abbreviation: "PG",
        city: "Prince George",
        goals: 0,
        logo: "https://assets.leaguestat.com/bchl/logos/14.jpg",
        penalties: 0,
        penalty_minutes: 0,
        powerplay_goals: 0,
        shots: 0,
        team_name: "Prince George Spruce Kings",
        venue:"Kopar Memorial Arena"
    },
    "Salmon Arm Silverbacks": {
        abbreviation: "SA",
        city: "Salmon Arm",
        goals: 0,
        logo: "https://assets.leaguestat.com/bchl/logos/20.jpg",
        penalties: 0,
        penalty_minutes: 0,
        powerplay_goals: 0,
        shots: 0,
        team_name: "Salmon Arm Silverbacks",
        venue:"Shaw Centre"
    },
    "Surrey Eagles": {
        abbreviation: "SUR",
        city: "Surrey",
        goals: 0,
        logo: "https://assets.leaguestat.com/bchl/logos/11.jpg",
        penalties: 0,
        penalty_minutes: 0,
        powerplay_goals: 0,
        shots: 0,
        team_name: "Surrey Eagles",
        venue:"Souoth Surrey Arena"
    },
    "Trail Smoke Eaters": {
        abbreviation: "TRA",
        city: "Trail",
        goals: 0,
        logo: "https://assets.leaguestat.com/bchl/logos/22.jpg",
        penalties: 0,
        penalty_minutes: 0,
        powerplay_goals: 0,
        shots: 0,
        team_name: "Trail Smoke Eaters",
        venue:"Cominco Arena"
    },
    "Vernon Vipers": {
        abbreviation: "VER",
        city: "Vernon",
        goals: 0,
        logo: "https://assets.leaguestat.com/bchl/logos/21.jpg",
        penalties: 0,
        penalty_minutes: 0,
        powerplay_goals: 0,
        shots: 0,
        team_name: "Vernon Vipers",
        venue:"Kal Tire Place"
    },
    "Victoria Grizzlies": {
        abbreviation: "VIC",
        city: "Victoria",
        goals: 0,
        logo: "https://assets.leaguestat.com/bchl/logos/18.jpg",
        penalties: 0,
        penalty_minutes: 0,
        powerplay_goals: 0,
        shots: 0,
        team_name: "Victoria Grizzlies",
        venue:"The Q Centre"
    },
    "West Kelowna Warriors": {
        abbreviation: "WK",
        city: "West Kelowna",
        goals: 0,
        logo: "https://assets.leaguestat.com/bchl/logos/19.jpg",
        penalties: 0,
        penalty_minutes: 0,
        powerplay_goals: 0,
        shots: 0,
        team_name: "West Kelowna Warriors",
        venue:"Royal LePage Place"
    }
};

export {
    teamNames
}